### ISSUE TITLE
[BUG] App Window is blank

### ISSUE THREAD

**Issue by ujo4eva** [ahmet-cetinkaya/whph#96]
### Describe the bug

I was on v0.15.0 and installed the v0.16.0 update almost right after it came out, tried opening it, it's just blank.

### Steps to reproduce

1. Go to github.com/ahmet-cetinkaya/whph
2. Go to releases
3. Download linux tar.gz (v0.16.0 - v0.16.1)
4. Extract and run whph

### Expected behavior

I expected to see my todo list

### App Version

0.16.0 - 0.16.1

### Device Model

HP Pavilion Gaming 15-dk-0387nia

### Operating System

Linux Mint 22.2

### Screenshots

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/65b832ef-b0ca-4ce3-b6c7-2579dafe6ba7" />

Edit: wrong versioning

**Comment by ahmet-cetinkaya** [comment]
Thanks for reporting this issue. We've identified and fixed the blank window problem caused by a general database issue affecting multiple platforms. The fix will be included in the next patch release.

**Comment by ahmet-cetinkaya** [comment]
Could you please test the next patch version once it's released and let us know if the blank window issue persists? This will help us ensure the database fix resolves the problem across all platforms.

**Comment by ujo4eva** [comment]
I'll check and give you feedback. Thanks for your prompt attention.

**Comment by ujo4eva** [comment]
Problem isn't fixed on either Linux or Android, I'm getting the same behaviour on both with v0.16.2

**Comment by ahmet-cetinkaya** [comment]
@ujo4eva I've made corrections that could have been causing the issue and added a dead screen so you can see the error message if you encounter an empty screen. Please try the new version
and let me know if the error continues. If it does, share the error message from the dead screen with me.

**Comment by ujo4eva** [comment]
Updated on my laptop and phone just now, the Android version appears to be working fine. I opened it, created a task, and "completed" said task without encountering an error.

Linux version on the other hand, showed the dead screen. My log should be in your email right now.

**Comment by ujo4eva** [comment]
Just downloaded the v0.16.4 release for Linux and it works now! Thanks!

**Comment by mechtronsystems** [comment]
I've had a problem with 16, including 16.4   on linux.
My habit_table had duplicate records.   I deleted them manually and 16.4 has started ok.
My habit_table has no unique constraint on id.   I have added the unique constraint manually.
This table was created with the initial install, somewhere around version 9 or 10.   If the unique is required, then the upgrade scripts have not added the unique.

**Comment by ahmet-cetinkaya** [comment]
Thanks @ujo4eva 🙏
Your feedback on both Android and Linux was really helpful.
I’m glad to hear that the issues are resolved in v0.16.4.

I’ll also be taking extra precautions to prevent this kind of problem from happening again.

I’m closing this issue, but please don’t hesitate to report it again if a similar problem arises in the future. 🚀

**Comment by ahmet-cetinkaya** [comment]
In beta versions, issues from previous releases can sometimes cause problems like this.

Glad you were able to fix it manually in your database file.

I’ll double-check the project’s database schemas regarding this.

Thanks again for your feedback, @mechtronsystems! 🙏

**Comment by ujo4eva** [comment]
*sigh

Sync doesn't appear to be working

**Comment by mechtronsystems** [comment]
> *sigh
> 
> Sync doesn't appear to be working

I deleted the sync config and re-configured.  Working ok now.

**Comment by ujo4eva** [comment]
> > *sigh
> > Sync doesn't appear to be working
> 
> I deleted the sync config and re-configured. Working ok now.

Still doesn't work for me after reinstalling. Both my devices still show all the tasks I had in v0.15.0, but when I try to set up sync, it fails. I've double-checked my firewall config and I attempted using the sync code and QR code methods as well. 

Should I open a new issue and post my logs?

**Comment by mechtronsystems** [comment]
I had some more sync problems after this.  I have deleted the Linux database and allowed whph to create a new one with the full new schema v28.   
Sync is now working and is very fast.   Imports and exports are working properly.   There were definitely issues with the legacy schema not being fully upgraded during version updates.

**Comment by ujo4eva** [comment]
Deleting the database doesn't fix the problem for me unfortunately

**Comment by ahmet-cetinkaya** [comment]
@ujo4eva Could you please create a backup using the Export option on your mobile device?
Then reinstall the app on both sides, import the backup on mobile, and try syncing again.

If the issue still persists, please enable logs in Advanced Settings and share them with me so I can take a closer look. 🙏

**Comment by ahmet-cetinkaya** [comment]
Continuing with #99
